version: "3.7"

services:
  mongo-rs0-1:
    image: "mongo-start"
    build: ./mongo-rs0-1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-rs0-1/data:/data/db
  mongo-rs0-2:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-rs0-2/data:/data/db
  mongo-rs0-3:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-rs0-3/data:/data/db
  setup-rs:
    image: "setup-rs"
    build: ./setup
    depends_on:
      - "mongo-rs0-1"
  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
  stock-trading-system-backend:
    depends_on: 
      - stock-trading-system-db
    build: ./backend
    container_name: stock-trading-system-backend
    volumes:
      - ./backend/src:/home/node/app/backend/src 
      - ./backend/typings:/home/node/app/backend/typings 
      - ./backend/tsconfig.json:/home/node/app/backend/tsconfig.json 
      - ./backend/.env:/home/node/app/backend/.env 
      - ./backend/coverage/:/home/node/app/backend/coverage/
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=stock-trading-system-mongo-rs0-1-1
      - DB_NAME=stock-trading-system-db
      - DB_PORT=27017
  stock-trading-system-frontend:
    build: ./frontend
    container_name: stock-trading-system-frontend
    depends_on: 
      - stock-trading-system-backend
    volumes:
      - ./frontend/src:/home/node/app/frontend/src 
      - ./frontend/tsconfig.json:/home/node/app/frontend/tsconfig.json
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
  
networks:
  mongodb-replica_default:
    driver: bridge