version: "3.7"

services:
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.4-bionic
    volumes:
      - ./data/mongo1:/var/lib/mongodb
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.4-bionic
    volumes:
      - ./data/mongo2:/var/lib/mongodb
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.4-bionic
    volumes:
      - ./data/mongo3:/var/lib/mongodb
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongosetup:
    image: mongo:4.4-bionic
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - .:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]
  adminmongo:
    image: "mrvautin/adminmongo"
    depends_on: 
      - mongo1
    ports:
      - "1234:1234"
    environment:
      - HOST=0.0.0.0
      - CONN_NAME=Docker
      - DB_HOST=mongo1
      - DB_PORT=27017
      - DB_NAME=stock-trading-system-db-docker
  stock-trading-system-backend:
    depends_on: 
      - mongo1
    build: ./backend
    container_name: stock-trading-system-backend
    volumes:
      - ./backend/src:/home/node/app/backend/src
      - ./backend/typings:/home/node/app/backend/typings
      - ./backend/tsconfig.json:/home/node/app/backend/tsconfig.json
      - ./backend/stockdata.json:/home/node/app/backend/stockdata.json
      - ./backend/.env:/home/node/app/backend/.env 
      - ./backend/coverage/:/home/node/app/backend/coverage/
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mongo1
      - DB_PORT=27017
      - CONN_NAME=stock-trading-system-db-docker
  stock-trading-system-frontend:
    build: ./frontend
    container_name: stock-trading-system-frontend
    depends_on: 
      - stock-trading-system-backend
    volumes:
      - ./frontend/src:/home/node/app/frontend/src 
      - ./frontend/tsconfig.json:/home/node/app/frontend/tsconfig.json
      - ./frontend/.prettierrc:/home/node/app/frontend/.prettierrc
      - ./nginx.conf:/usr/share/nginx/html/nginx.conf
    restart: always
    expose:
      - "80"
    ports:
      - "8080:80"