version: "3.7"

services:
  stock-trading-system-backend:
    depends_on: 
      - stock-trading-system-db
    build: ./backend
    container_name: stock-trading-system-backend
    volumes:
      - ./backend/src:/home/node/app/backend/src 
      - ./backend/tsconfig.json:/home/node/app/backend/tsconfig.json 
      - ./backend/coverage/:/home/node/app/backend/coverage/
    restart: always
    expose:
      - "8000"
    ports:
      - "8000:8000"
  stock-trading-system-frontend:
    build: ./frontend
    container_name: stock-trading-system-frontend
    depends_on: 
      - stock-trading-system-backend
    volumes:
      - ./frontend/src:/home/node/app/frontend/src 
      - ./frontend/tsconfig.json:/home/node/app/frontend/tsconfig.json
    restart: always
    expose:
      - "8080"
    ports:
      - "8080:8080"
  mongo:
    container_name: stock-trading-system-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - ~/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password